name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
 - type: markdown
   attributes:
    value: |
     Thanks for taking the time to fill out this bug report!

 - type: textarea
   id: what-happened
   attributes:
    label: What happened?
    description: Describe the bug and what you expected to happen
    placeholder: Tell us what you see!
   validations:
    required: true

 - type: textarea
   id: steps
   attributes:
    label: Steps to Reproduce
    description: How can we reproduce this issue?
    placeholder: |
     1. Go to '...'
     2. Click on '....'
     3. Scroll down to '....'
     4. See error
   validations:
    required: true

 - type: textarea
   id: environment
   attributes:
    label: Environment
    description: What browser/OS are you using?
    placeholder: |
     - OS: [e.g. Windows 10, macOS 12.0]
     - Browser: [e.g. Chrome 96, Firefox 95]
     - Version: [e.g. 1.0.0]
   validations:
    required: false

 - type: textarea
   id: additional
   attributes:
    label: Additional Context
    description: Add any other context about the problem here
   validations:
    required: false