name: 🐛 Bug Report
description: File a bug report for development issues
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-summary
    attributes:
      label: Bug Summary
      description: Brief description of the issue
      placeholder: "e.g., Shape order IndexOutOfBounds exception when deleting layers"
    validations:
      required: true

  - type: textarea
    id: error-details
    attributes:
      label: Error Details
      description: Detailed error information
      placeholder: |
        - Error message/stack trace
        - Console logs
        - Exception type
        - Error code (if any)
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps to reproduce the issue
      placeholder: |
        1. Open application
        2. Create new layer
        3. Select shape tool
        4. Click delete
        5. Error occurs
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Layer should be deleted without errors"
    validations:
      required: true

  - type: textarea
    id: code-context
    attributes:
      label: Code Context
      description: Related code, methods, or components
      placeholder: |
        - Affected class/method: ShapeController.deleteShape()
        - Related files: TabManager.js, Constants.js
        - Component: Layer management system
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (App crashes/data loss)
        - High (Major functionality broken)
        - Medium (Feature not working)
        - Low (Minor issue/cosmetic)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Development environment details
      placeholder: |
        - OS: Windows 10
        - IDE: IntelliJ IDEA 2025.1
        - Java Version: 21
        - Framework: JavaFX
        - Branch: feature/layer-management
    validations:
      required: false